const photoInput=document.getElementById("photo"),preview=document.getElementById("preview"),previewWrap=document.getElementById("preview-wrap"),analyzeBtn=document.getElementById("analyze-btn"),statusEl=document.getElementById("status"),resultPanel=document.getElementById("result-panel"),resultContent=document.getElementById("result-content"),saveBtn=document.getElementById("save-btn"),againBtn=document.getElementById("again-btn"),modeBanner=document.getElementById("mode-banner"),statsPill=document.getElementById("stats-pill");let current=null;
async function refreshStats(){try{const r=await fetch("/api/stats"),s=await r.json();statsPill.textContent=`★ ${s.total_xp} XP · Lv ${s.level}`}catch{}}
async function refreshMode(){try{const r=await fetch("/api/health"),d=await r.json();modeBanner.textContent=d.mode==="demo"?"ONLINE DEMO MODE · Full local AI runs with Ollama + Qwen3-VL 2B on your computer.":d.ollama?.connected&&d.ollama?.model_ready?"LOCAL AI READY · Ollama + Qwen3-VL 2B":"LOCAL AI · Start Ollama to analyze photos with Qwen3-VL 2B."}catch{modeBanner.textContent="Local-first AI · Ollama + Qwen3-VL 2B"}}
photoInput.addEventListener("change",()=>{const f=photoInput.files?.[0];if(!f)return;preview.src=URL.createObjectURL(f);previewWrap.classList.remove("hidden");analyzeBtn.disabled=false;statusEl.textContent="";resultPanel.classList.add("hidden")});
document.getElementById("start-btn").addEventListener("click",()=>document.getElementById("explore").scrollIntoView({behavior:"smooth"}));
analyzeBtn.addEventListener("click",async()=>{const f=photoInput.files?.[0];if(!f)return;analyzeBtn.disabled=true;statusEl.textContent="Looking closely at your discovery…";resultPanel.classList.add("hidden");const form=new FormData;form.append("file",f);try{const r=await fetch("/api/analyze",{method:"POST",body:form}),d=await r.json();if(!r.ok)throw new Error(d.detail||"Analysis failed.");current=d;renderResult(d);resultPanel.classList.remove("hidden");resultPanel.scrollIntoView({behavior:"smooth"})}catch(e){statusEl.textContent=e.message}finally{analyzeBtn.disabled=false}});
function renderResult(d){const r=d.result;resultContent.innerHTML=`<div class="discovery-head"><span class="badge">${escapeHtml(r.category)}</span><span class="badge confidence">${escapeHtml(r.confidence)}</span>${d.mode==="demo"?'<span class="badge">DEMO</span>':""}</div><h2 class="discovery-title">${escapeHtml(r.name)}</h2><p class="muted">${escapeHtml(r.description)}</p><h3>Interesting facts</h3><ul class="fact-list">${r.facts.map(f=>`<li>${escapeHtml(f)}</li>`).join("")}</ul><div class="challenge"><strong>🎯 Your next outdoor challenge</strong>${escapeHtml(r.outdoor_challenge)}</div><div class="xp">+ ${d.xp.xp_awarded} XP</div>`;}
saveBtn.addEventListener("click",async()=>{if(!current)return;saveBtn.disabled=true;try{const r=await fetch("/api/discoveries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({result:current.result,upload_path:current.upload_path,xp_awarded:current.xp.xp_awarded})}),d=await r.json();if(!r.ok)throw new Error(d.detail||"Could not save.");statusEl.textContent=`Saved! +${d.xp_awarded} XP added to your journal.`;saveBtn.textContent="Saved ✓";refreshStats()}catch(e){statusEl.textContent=e.message}finally{saveBtn.disabled=false}});
againBtn.addEventListener("click",()=>{photoInput.value="";previewWrap.classList.add("hidden");resultPanel.classList.add("hidden");analyzeBtn.disabled=true;statusEl.textContent=""});
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#39;"}[c]))} refreshStats();refreshMode();